name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag test:$GITHUB_SHA

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v1.6.1
      with:
        # private SSH key
        private-key: ${{ secrets.SSH_KEY }}
        known-hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: send to server
      run: docker save test | ssh -p ${{ secrets.REMOTE_PORT }} ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "docker load"
    
    - name: deploy to dokku
      uses: appleboy/ssh-action@master
      env:
        NAME: test:${{ github.sha }}
        SECRET_KEY: ${{  secrets.SECRET_KEY }}
        MAILGUN_KEY: ${{  secrets.MAILGUN_KEY }}
        EMAIL_DOMAIN: ${{  secrets.EMAIL_DOMAIN }}
        SITE_DOMAIN: ${{  secrets.SITE_DOMAIN }}
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.REMOTE_PORT }}
        envs: NAME,SECRET_KEY,MAILGUN_KEY,EMAIL_DOMAIN,SITE_DOMAIN
        script: |
          docker tag $NAME dokku/test:latest
          dokku config:set test SECRET_KEY=$SECRET_KEY MAILGUN_KEY=$MAILGUN_KEY EMAIL_DOMAIN=$EMAIL_DOMAIN SITE_DOMAIN=$SITE_DOMAIN
          dokku tags:deploy test
